pipeline {
    agent any
    stages {
        stage('Check Changes') {
            steps {
                 script {
                    // SAFER Git diff
                    def diff = sh(script: "git fetch origin main && git diff --name-only origin/main...HEAD", returnStdout: true).trim()
                    echo "Changed files:\n${diff}"

                    if (!diff.split('\n').any { it.startsWith('MLOps_frontend/') }) {
                        echo "No changes in MLOps_frontend. Skipping pipeline."
                        currentBuild.result = 'NOT_BUILT'
                        return
                    }
                }
            }
        }
        stage('Test run') {
            steps {
                echo "Test Run ..."
            }
        }
    }
    post {
        success {
            echo "✅ Pipeline executed successfully."
        }
        failure {
            echo "❌ Pipeline failed!"
        }
    }
}

