pipeline {
    agent any
    stages {
        stage('Check Changes') {
            steps {
                script {
                    def diff = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim()
                    if (!diff.split('\n').any { it.startsWith('MLOps-frontend/') }) {
                        echo "No changes in MLOps-frontend. Skipping pipeline."
                        currentBuild.result = 'NOT_BUILT'
                        return
                    }
                }
            }
        stage('Test run') {
            steps {
                echo "Test Run ..."
            }
        }
    }
    post {
        success {
            echo "✅ Pipeline executed successfully."
        }
        failure {
            echo "❌ Pipeline failed!"
        }
    }
}
