stages:
  data_import:
    cmd: python scripts/data_import.py
    deps:
      - scripts/data_import.py
    params:
      - data_import.file_size
    outs:
      - Data/Raw
  data_preprocessing:
    cmd: python scripts/data_preprocessing.py
    deps:
      - Data/Raw
      - scripts/data_preprocessing.py
    outs:
      - Data/Clean
  tokenizer:
    cmd: python scripts/tokenizer.py
    deps:
      - Data/Clean
      - scripts/tokenizer.py
    params:
      - tokenizer.vocab_size
    outs:
      - Joblibs/tokenizer.joblib
  transformer_training:
    cmd: PYTHONPATH=/Users/prakhar_patil/Desktop/SPE_Proj python scripts/transformer_training.py
    deps:
      - scripts/transformer_training.py
      - Model/model_architecture.py
      - Joblibs/tokenizer.joblib
      - Data/Clean
    outs:
      - checkpoints/
  transformer_evaluation:
    cmd: python transformer_evaluation.py
    deps:
      - evaluate_transformer.py
      - Joblibs/tokenizer.joblib
      - Joblibs/transformer.joblib
      - Data/Clean/L4_cleaned.txt
    params:
      - transformer_evaluation.block_size
    outs:
      - Evaluation/eval_metrics.json
    metrics:
      - Evaluation/eval_metrics.json:
          cache: false


